import type { Idl } from '@coral-xyz/anchor';
import { PublicKey } from '@solana/web3.js';

// Generated by `anchor build` — single source of truth:
// <repo>/target/idl/carbon_credit_tokenizer.json
import idlJson from '@carbon-token/idl';

/** Anchor 0.31 IDL (matches `@coral-xyz/anchor` 0.31 `Idl`). */
export const IDL = idlJson as Idl;

/** Must match the deployed program; kept in sync with the IDL `address` field. */
export const PROGRAM_ID = new PublicKey(idlJson.address);

// Solana network configuration
export const NETWORK = 'devnet';
export const RPC_ENDPOINT = 'https://api.devnet.solana.com';
